Examples('the fail function',
  Example('errors with given argument and correct file/line info',
    Given(Named_source('the_file.pp', @(SRC)),
    #
    #
    fail('too bad')
    |-SRC
    ),
    Evaluates_with(Error('too bad (file: the_file.pp, line: 3, column: 1)'))),

  Example('errors with given concatenated and stringified arguments',
    Given(`fail('the hash', {a => [32]}, 'did not have b')`),
    Evaluates_with(Error(Contain(`the hash {'a' => [32]} did not have b`)))),
)